### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by joshuaconner** [SublimeText/AdvancedNewFile#78]
When I install this plugin in ST3 I get the following error in the ST console and lots of things (including Package Control commands from the command palette) stop working until I manually remove the `.sublime-package` file from my `Installed Packages` folder:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 140, in create_window_commands
    cmds.append(class_(window))
  File "advanced_new_file.commands.delete_file_command in /Users/joshuaconner/Library/Application Support/Sublime Text 3/Installed Packages/AdvancedNewFile.sublime-package", line 13, in __init__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

Any ideas?

**Comment by povellesto** [comment]
Thanks for helping me Joshaconner
